# Generated by Django 6.0.5 on 2026-08-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(choices=[('saree', 'Saree'), ('menswear', 'Menswear'), ('other', 'Other')], db_index=True, default='other', max_length=10),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('fabric', 'Fabric'), ('weave', 'Weave'), ('zari', 'Zari'), ('border', 'Border'), ('pallu', 'Pallu'), ('work', 'Work'), ('origin', 'Origin')], db_index=True, max_length=24)),
                ('value_slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key', 'sort_order', 'label'],
                'unique_together': {('key', 'value_slug')},
            },
        ),
    ]
