# Generated by Django 6.0.5 on 2026-08-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_attribute_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='border',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'border'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_border', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'fabric'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_fabric', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'origin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_origin', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='pallu',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'pallu'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_pallu', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='silk_mark_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weave',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'weave'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_weave', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='work',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'work'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_work', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='zari',
            field=models.ForeignKey(blank=True, limit_choices_to={'key': 'zari'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_zari', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='blouse_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
