# Generated by Django 6.0.5 on 2026-08-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_backfill_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='zari_type',
        ),
    ]
