# Generated by Django 6.0.5 on 2026-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_tryonsession_customer_photo_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryonsession',
            name='customer_photo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tryonsession',
            name='result_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
